#!/usr/bin/env bash
# Install and configure HAproxy on lb-01 server.
sudo apt update -y
sudo apt install haproxy -y
configuration="
frontend r_frontend
    bind *:80
    default_backend r_backend

backend r_backend
	balance roundrobin
	server 138850-web-01 100.24.236.144 check port 80
	server 138850-web-02 54.172.42.190 check port 80
"
sudo chown -R "$USER":"$USER" /etc/haproxy/
echo "$configuration" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
